// Generated by https://quicktype.io

export class ApiEndpoints {
  base: string = 'https://yoga-api-nzy4.onrender.com/v1';
  categories: string = 'https://yoga-api-nzy4.onrender.com/v1/categories';
  'category-by-id': string =
    'https://yoga-api-nzy4.onrender.com/v1/categories?id=value';
  'category-by-name': string =
    'https://yoga-api-nzy4.onrender.com/v1/categories?name=value';
  'category-by-id-level': string =
    'https://yoga-api-nzy4.onrender.com/v1/categories?id=value&level=value';
  poses: string = 'https://yoga-api-nzy4.onrender.com/v1/poses';
  'pose-by-id': string = 'https://yoga-api-nzy4.onrender.com/v1/poses?id=';
  'pose-by-name': string = 'https://yoga-api-nzy4.onrender.com/v1/poses?name=';
  'poses-by-level': string =
    'https://yoga-api-nzy4.onrender.com/v1/poses?level=beginner';
}
// Generated by https://quicktype.io
